services:
  - type: web
    name: cold-search-premium-api
    env: python
    region: frankfurt
    buildCommand: |
      apt-get update && apt-get install -y unrar
      pip install -r requirements.txt
    startCommand: python app.py
